  # EC2 oriented: windowed + docker + GNU parallel
  ec2_windowed:
    <<: *default_windowed
    description: "For DAC use on EC2"
    mode: "region"
    tools:
      container_type: "docker"
      resource_mgmt: "parallel"
    container:
      docker_image: "path_to/stefinfection/rufus:latest"