#!/bin/bash

usage() {
	echo "Usage: $0 -s <subject> -w <window_size> [-h]"
	echo "Options:"
	echo " -s subject_file	Required: The name of the subject file: must be the same as that supplied to the RUFUS run"
	echo " -w window_size	Required: The window size used for the RUFUS run (0 for whole genome mode)"
	echo " -h help	Print help message"
	exit 1
}

# Cleans up intermediate files, reports no variants found in both out + error, and exits failure code
clean_up_post_temps() {
  files=("$TEMP_FINAL_VCF")

  for file in "${files[@]}"; do
	if [ "$file" != "" ]; then
    	find . -maxdepth 1 -type f -name "$file*" -delete
	fi
  done

  find . -maxdepth 1 -type f -name "temp.RUFUS.Final*vcf.gz*" -delete
  find . -maxdepth 1 -type f -name "regions.chunk.*" -delete
  find . -maxdepth 1 -type f -name "regions.txt" -delete
  find . -maxdepth 1 -type f -name "final.list" -delete
  rm -f "$MERGED" "$NO_HEAD" "rufus.cmd"
  find . -type d -name "Intermediates" -exec rm -rf {} +
  find . -type d -name "TempOverlap" -exec rm -rf {} +
}
trap 'clean_up_post_temps' EXIT

# parse command line arguments
SUBJECT_FILE=""

while getopts "hw:s:" option; do 
	case $option in 
		h) usage;;
		s) SUBJECT_FILE=$OPTARG;;
		w) WINDOW_SIZE=$OPTARG;;
		\?) echo "Invalid option: -$OPTARG" >&2
		    usage;;	
		*) echo "Option -$OPTARG requires an argument" >&2
		   usage;;
	esac
done
shift $((OPTIND-1))

if [[ -z "$SUBJECT_FILE" ]]; then
	echo "ERROR: Missing required option -s (subject cram/bam)" >&2
	usage
fi

if [[ -z "$WINDOW_SIZE" ]]; then
	echo "ERROR: Missing required option -w (window size)" >&2
	usage
fi


echo "RUFUS post-process version d-1.1.9"
date
start_time=$(date +"%s")

# Have to define all of these before first possible exit
SUBJECT_STRING=$(basename "$SUBJECT_FILE")
TEMP_FINAL_VCF="temp.RUFUS.Final.${SUBJECT_STRING}.combined.vcf.gz"
TEMP_PREFILTERED_VCF="temp.RUFUS.Prefiltered.${SUBJECT_STRING}.combined.vcf.gz"
FINAL_VCF="RUFUS.Final.${SUBJECT_STRING}.vcf"

# Slight name change if not doing a windowed run. The calling stage writes the whole-genome file with
# a .wg region postfix (temp.RUFUS.Final.<subject>.wg.vcf.gz), so match that here.
if [ "$WINDOW_SIZE" -eq 0 ]; then
	TEMP_FINAL_VCF="temp.RUFUS.Final.${SUBJECT_STRING}.wg.vcf.gz"
fi

# Check to see if temp vcf(s) exists, if not report empty results and exit
if read -r first_match < <(compgen -G "temp.RUFUS.Final*vcf.gz"); then
    echo "Found temporary vcf(s)"
else
  	echo "Could not find any temporary vcf(s) from calling stage. Exiting..."
	exit 1
fi

# Summarize region status log if present (generated by runRufus.sh in region mode)
REGION_LOG="region_status.log"
if [ -f "$REGION_LOG" ] && [ "$WINDOW_SIZE" -ne 0 ]; then
	total=$(wc -l < "$REGION_LOG")
	called=$(grep -c "VARIANTS_CALLED" "$REGION_LOG" || true)
	nocall=$(grep -c "NO_VARIANTS" "$REGION_LOG" || true)
	errors=$(grep -c "ERROR" "$REGION_LOG" || true)
	echo "========== Region Status Summary =========="
	printf "Total regions: %d\n" "$total"
	printf "  Variants called: %d\n" "$called"
	printf "  No variants:     %d\n" "$nocall"
	printf "  Errors:          %d\n" "$errors"
	if [ "$nocall" -gt 0 ]; then
		echo "--- No-variant breakdown ---"
		grep "NO_VARIANTS" "$REGION_LOG" | cut -f3 | sort | uniq -c | sort -rn
	fi
	if [ "$errors" -gt 0 ]; then
		echo "--- Error breakdown ---"
		grep "ERROR" "$REGION_LOG" | cut -f2,3 | sort | uniq -c | sort -rn
	fi
	echo "==========================================="
	echo "Full region log: $(realpath "$REGION_LOG")"
fi

MERGED="merged.vcf"
NO_HEAD="no_header.vcf"
FINAL_GZ="${FINAL_VCF}.gz"

# Concat vcfs if in windowed mode
if [ "$WINDOW_SIZE" -ne 0 ]; then
	# Concatenate all intermediates
	find . -maxdepth 1 -type f -name 'temp.RUFUS.Final.*.vcf.gz' -print |
	sort -V > regions.txt

	split -l 200 regions.txt regions.chunk.

	for f in regions.chunk.*; do
			echo "-- BCFTools ---------------------------"
			bcftools concat -a -D -f $f -Oz -o "$f".vcf.gz
			bcftools index "$f".vcf.gz
	done

	ls regions.chunk.*.vcf.gz > final.list
	bcftools concat -a -D -f final.list -Ov -o $MERGED

	bcftools sort -T "tmp_bcftools.XXXXXX" -Ov -o "$NO_HEAD" "$MERGED" \
	|| { echo "Error: bcftools sort failed"; exit 1; }

else
	# Just sort and add header for whole genome mode
	bcftools sort -T "tmp_bcftools.XXXXXX" -Ov -o "$NO_HEAD" "$TEMP_FINAL_VCF" \
		|| { echo "Error: bcftools sort failed"; exit 1; }
fi

# Build final VCF with correct header
# Strip per-region RUFUSCommandLine and inject full-run rufus.cmd instead
RUFUS_CMD_FILE="rufus.cmd"
if [ "$WINDOW_SIZE" -ne 0 ] && [ -f "$RUFUS_CMD_FILE" ]; then
	bcftools view -h "$NO_HEAD" | grep -v "^##RUFUSCommandLine" | head -n -1 > "$FINAL_VCF" \
		|| { echo "Error: bcftools view on merged vcf failed"; exit 1; }
	cat "$RUFUS_CMD_FILE" >> "$FINAL_VCF"
	echo "##RUFUS_runMode=region (window_size=${WINDOW_SIZE})" >> "$FINAL_VCF"
	bcftools view -h "$NO_HEAD" | tail -n 1 >> "$FINAL_VCF"
else
	bcftools view -h "$NO_HEAD" | head -n -1 > "$FINAL_VCF" \
		|| { echo "Error: bcftools view on merged vcf failed"; exit 1; }
	bcftools view -h "$NO_HEAD" | tail -n 1 >> "$FINAL_VCF"
fi
bcftools view -H "$NO_HEAD" >> "$FINAL_VCF"

bgzip "$FINAL_VCF" || { echo "Error: bgzip failed on final vcf"; exit 1; }
tabix -f -p vcf "$FINAL_GZ" \
|| { echo "Error: tabix failed"; exit 1; }
echo "-----------------------------------------"
echo "Done: $FINAL_GZ"

echo "Concatenating & sorting complete."
end_time=$(date +"%s")
time_delta=$(( end_time - start_time ))
hours=$(( time_delta / 3600 ))
minutes=$(( (time_delta % 3600) / 60 ))
seconds=$(( time_delta % 60 ))
printf "RUFUS combine stage completed in: %02d:%02d:%02d\n" $hours $minutes $seconds