# This script removes inherited variants called by rufus which lie on the same contig as
# a somatic variant. It accomplishes this task by performing a pileup and variant call
# in the control bam for each of the rufus-identified variants, then taking the complement
# of the control set in an intersection.
set -euo pipefail

: "${WORK_DIR:?WORK_DIR must be set}"

# parse command line arguments
REFERENCE_FILE=""  # Reference file (.fa) - must be the same as RUFUS run that generated RUFUS_VCF
RUFUS_VCF=""       # The 'FINAL' vcf generated by rufus, to be isec'd
OUT_VCF=""
SRC_DIR=""
WINDOW_SIZE="1000"
FMTD_REGION=""
CONTROL_BAM_LIST=() # Remaining args, all control bams
THREADS=10

cleanup() {
    rm -rf "$WORK_DIR"/*_temp_pileups
    rm -f "$WORK_DIR"/temp_aligned.*."$FMTD_REGION".bam
}
trap cleanup EXIT

while getopts "h:f:i:o:w:r:c:t:" option; do 
	case $option in 
		h) usage;;
		f) REFERENCE_FILE=$OPTARG;;
		i) RUFUS_VCF=$OPTARG;;
		o) OUT_VCF=$OPTARG;;
		w) WINDOW_SIZE=$OPTARG;;
		r) FMTD_REGION=$OPTARG;;
		t) THREADS=$OPTARG;;
		c) IFS=',' read -r -a CONTROL_BAM_LIST <<< "$OPTARG";;
		\?) echo "Invalid option: -$OPTARG" >&2
		    usage;;	
		*) echo "Option -$OPTARG requires an argument" >&2
		   usage;;
	esac
done
shift $((OPTIND-1))

if [[ -z "$RUFUS_VCF" ]]; then
	echo "ERROR: Missing required option -i (rufus input vcf)" >&2
	exit 1
fi
if [[ -z "$OUT_VCF" ]]; then
	echo "ERROR: Missing required option -o (output vcf name)" >&2
	exit 1
fi
if [[ -z "$REFERENCE_FILE" ]]; then
	echo "ERROR: Missing required option -f (reference fasta)" >&2
	exit 1
fi
if [[ -z "$FMTD_REGION" ]]; then
	echo "ERROR: Missing required option -r (region)" >&2
	exit 1
fi

# ENV file override
: "${RUFUS_ROOT:=/opt/RUFUS}"

# static vars
CONTROL_VCF="$WORK_DIR/isec_control.$FMTD_REGION.vcf.gz"
NORMED_VCF="$WORK_DIR/normed.$(basename "$RUFUS_VCF")"
BWA="$RUFUS_ROOT/bin/externals/bwa/src/bwa_project/bwa"
PILEUP_SCRIPT="$RUFUS_ROOT/post_process/single_pileup.sh"

# make intersection directory
ISEC_OUT_DIR="$WORK_DIR/temp_${FMTD_REGION}_isecs"
mkdir -p $ISEC_OUT_DIR

# Two representations of the subject calls, deliberately (issue #98):
#   NORMED_VCF  left-aligned and trimmed, composite alleles INTACT -- this is what we EMIT.
#   ATOMS_VCF   the same records decomposed, each atom carrying INFO/OLD_REC pointing back at its
#               parent -- this is what we MATCH on, and it is never emitted.
#
# The decomposition is load-bearing and cannot simply be dropped. CONTROL_VCF is produced by
# `bcftools call`, which has no MNP model and only ever emits per-position SNVs and indels, so a
# composite subject record can never string-match a control record. Without atoms, every inherited
# block substitution would be retained as a false somatic call. Only the OUTPUT representation has to
# stay composite -- emitting the surviving atoms of a partially-matched record instead would assert a
# haplotype the subject does not carry.
vt normalize -n "$RUFUS_VCF" -r "$REFERENCE_FILE" | bgzip > "$NORMED_VCF"
bcftools index -t "$NORMED_VCF"

ATOMS_VCF="$WORK_DIR/atoms.$(basename "$RUFUS_VCF")"
bcftools norm -a --old-rec-tag OLD_REC -f "$REFERENCE_FILE" "$NORMED_VCF" -Oz -o "$ATOMS_VCF"
bcftools index -t "$ATOMS_VCF"

# Parent key for a record: its OLD_REC minus the trailing USED_ALT_IDX, or its own coordinates when
# `norm -a` left it untouched and emitted OLD_REC="." . For a multiallelic parent OLD_REC carries the
# FULL alt list (e.g. chr20|30000|TGG|TTT,GGG|2), so this key matches the parent record's own
# CHROM/POS/REF/ALT exactly, and atoms from different ALTs group under the one parent.
parent_keys() {
	bcftools query -f '%INFO/OLD_REC\t%CHROM|%POS|%REF|%ALT\n' "$1" | awk -F'\t' '
		{ if ($1 == "." || $1 == "") { print $2 }
		  else { n = split($1, a, "|"); printf "%s|%s|%s|%s\n", a[1], a[2], a[3], a[4] } }'
}

#for loop for each control file provided by user
MERGED_PILEUP="$WORK_DIR/merged_pileup.${FMTD_REGION}.vcf.gz"
SORTED_MERGED_PILEUP="$WORK_DIR/sorted.merged_pileup.${FMTD_REGION}.vcf.gz"

pileups=()
for CONTROL in "${CONTROL_BAM_LIST[@]}"; do
	echo "Piling up $CONTROL" >&2

    MADE_ALIGN_CONTROL=false
	CONTROL_BAM=""

	# Make temp dir for individual pileups
	CONTROL_TAG=$(basename "$CONTROL")
	CONTROL_TAG="${CONTROL_TAG%.bam}"
	CONTROL_TAG=${CONTROL_TAG}.${FMTD_REGION}
	CURR_MERGED_PILEUP="$WORK_DIR/${CONTROL_TAG}.ctrl.merged_pileup.vcf.gz"
	CURR_PILEUP_DIR="$WORK_DIR/${CONTROL_TAG}_temp_pileups"
	CONTROL_ALIGNED="$WORK_DIR/temp_aligned.${CONTROL_TAG}.bam"
 
    #check to see if the provided bam file is aligned
    if [ "$(samtools view -H "$CONTROL" | grep -c '^@SQ')" -gt 0 ]; then
        CONTROL_BAM=$CONTROL
    else
		# TODO: this really needs to be aligned, otherwise we'd be doing this 3000+ times
        "$BWA" mem -t 10 "$REFERENCE_FILE" "$CONTROL" | samtools view -S -@ 12 -b - > "$CONTROL_ALIGNED"
        CONTROL_BAM="$CONTROL_ALIGNED"
	    MADE_ALIGN_CONTROL=true
    fi
    
    # Run pileup and call variants
	echo "Starting parallel mpileup..."
	export PILEUP_SCRIPT CURR_PILEUP_DIR
	
	# Running in WG mode, split pileup by chr
	if [ "$WINDOW_SIZE" -ne 0 ]; then
		# Likely dealing with a small number of variants, send in a single list of sites
		# Regions come from ATOMS_VCF, not NORMED_VCF: a composite record reports only its start
		# position, so piling up the parent alone would miss its later atom positions entirely.
		regions=$(bcftools view -H "$ATOMS_VCF" | awk '!/^#/ {printf "%s%s:%d-%d", sep, $1, $2, $2; sep=","} END{print ""}')
		bash $PILEUP_SCRIPT "$regions" "${CONTROL_BAM}" "${REFERENCE_FILE}" > "$CURR_MERGED_PILEUP"
	else
		# Better to do chromosome by chromosome for speed for entire genome
		TEMP_ARGS_FILE="$WORK_DIR/$FMTD_REGION.arguments.txt"
		mkdir -p "$CURR_PILEUP_DIR"
		bcftools query -f '%CHROM\n' "$ATOMS_VCF" | sort | uniq | \
		awk -v bam="$CONTROL_BAM" -v ref="$REFERENCE_FILE" '{print $1 "\t" bam "\t" ref}' > "$TEMP_ARGS_FILE"
		cat "$TEMP_ARGS_FILE" | parallel -j +0 --colsep '\t' "bash \"$PILEUP_SCRIPT\" {1} {2} {3} > $CURR_PILEUP_DIR/{1}.vcf.gz"
		for vcf in "$CURR_PILEUP_DIR"/*vcf.gz; do
			bcftools index "$vcf"
		done
		# TODO: this needs to be tested - whole genome 
		bcftools concat -Oz -o "$CURR_MERGED_PILEUP" "$CURR_PILEUP_DIR"/*.vcf.gz
		rm "$TEMP_ARGS_FILE"
		rm -r "$CURR_PILEUP_DIR"
	fi

	bcftools index "$CURR_MERGED_PILEUP"
	pileups+=("$CURR_MERGED_PILEUP")
done

# Combine control specific pileups if there are multiple
if [ "${#pileups[@]}" -gt 1 ]; then
	echo "about to merge ${pileups[@]}"
	total_records=$(for p in "${pileups[@]}"; do bcftools view -H "$p"; done | wc -l)
    if [ "$total_records" -eq 0 ]; then
        cp "${pileups[0]}" "$MERGED_PILEUP"
        bcftools index "$MERGED_PILEUP"
    else
        bcftools merge -Oz -o "$MERGED_PILEUP" "${pileups[@]}"
    fi
else
	cp "${pileups[0]}" "$MERGED_PILEUP"
fi
rm -f $WORK_DIR/*."$FMTD_REGION".ctrl.merged_pileup.vcf.gz*

# Sort combined pileups
bcftools sort -Oz -o "$SORTED_MERGED_PILEUP" "$MERGED_PILEUP"
bcftools index "$SORTED_MERGED_PILEUP"
rm -f $MERGED_PILEUP

# Call variants from merged pileup vcf
echo "Starting pileup call..."
bcftools view -e 'ALT="<*>" && N_ALT=1' "$SORTED_MERGED_PILEUP" | bcftools call -mv -Oz -o "$CONTROL_VCF"
bcftools index "$CONTROL_VCF"
rm "$SORTED_MERGED_PILEUP"*

# ---------------------------------------------------------------------------------------------
# All-atoms rule (issue #98).
#
# A parent record is dropped only when EVERY one of its atoms was found in the control. Partial
# inheritance of a haplotype does not make the haplotype inherited: a somatic change adjacent to a
# germline variant is a real and common situation, and the previous behaviour -- emitting whichever
# atoms survived `isec -n=1 -w1` -- turned it into a fabricated variant. Worked example:
#
#   subject call        chr20:20000  AAC>CTG      one MNP, one haplotype
#   control germline    chr20:20000  A>C
#   old behaviour       emits 20001 A>T and 20002 C>G, asserting reference A at 20000 -- a haplotype
#                       the subject does not carry
#   all-atoms rule      keeps chr20:20000 AAC>CTG whole, annotated CO_ATOMS=1/3
# ---------------------------------------------------------------------------------------------
CONTROL_RECORD_COUNT=$(bcftools view -H "$CONTROL_VCF" | wc -l)
MATCHED_COUNTS="$WORK_DIR/matched_atoms.$FMTD_REGION.txt"
ATOM_TOTALS="$WORK_DIR/atom_totals.$FMTD_REGION.txt"
KEEP_TSV="$WORK_DIR/keep_parents.$FMTD_REGION.tsv"

if [ "$CONTROL_RECORD_COUNT" -eq 0 ]; then
	echo "Control VCF has zero variant records — nothing can be co-inherited."
	: > "$MATCHED_COUNTS"
else
	echo "Starting intersection..."
	# -n=2 -w1: atoms present in BOTH files, written from file 1 (the subject's atoms). The previous
	# code used -n=1 to take the survivors directly; we need the MATCHES so they can be counted per
	# parent instead of emitted.
	bcftools isec -Oz -w1 -n=2 -p "$ISEC_OUT_DIR" "$ATOMS_VCF" "$CONTROL_VCF"
	parent_keys "$ISEC_OUT_DIR/0000.vcf.gz" | sort | uniq -c | awk '{print $2"\t"$1}' > "$MATCHED_COUNTS"
fi

parent_keys "$ATOMS_VCF" | sort | uniq -c | awk '{print $2"\t"$1}' > "$ATOM_TOTALS"

awk -F'\t' '
	NR==FNR { matched[$1] = $2; next }
	{
		total = $2 + 0
		m = ($1 in matched) ? matched[$1] + 0 : 0
		if (m >= total) next            # every atom inherited -> drop this parent
		print $1 "\t" m "/" total
	}' "$MATCHED_COUNTS" "$ATOM_TOTALS" > "$KEEP_TSV"

echo "Co-inheritance: keeping $(wc -l < "$KEEP_TSV") of $(wc -l < "$ATOM_TOTALS") record(s)."

# Emit the surviving PARENT records, composite alleles intact, annotated with CO_ATOMS. Done in awk
# rather than `bcftools view -T` because the selection is per REF/ALT, not per position: two records
# can share a position and only one of them be fully inherited.
zcat "$NORMED_VCF" | awk -F'\t' -v OFS='\t' '
	NR==FNR { co[$1] = $2; next }
	/^#CHROM/ {
		print "##INFO=<ID=CO_ATOMS,Number=1,Type=String,Description=\"Atoms of this record found in the control / total atoms. A record is dropped only when all of its atoms are found, so a partially-inherited haplotype is kept whole.\">"
		print; next
	}
	/^#/ { print; next }
	{
		key = $1 "|" $2 "|" $4 "|" $5
		if (!(key in co)) next
		$8 = ($8 == "." || $8 == "") ? "CO_ATOMS=" co[key] : $8 ";CO_ATOMS=" co[key]
		print
	}' "$KEEP_TSV" - | bgzip > "$OUT_VCF"
bcftools index -t -f "$OUT_VCF"

rm -f "$MATCHED_COUNTS" "$ATOM_TOTALS" "$KEEP_TSV" "$ATOMS_VCF" "$ATOMS_VCF".tbi
rm "$CONTROL_VCF"*

# Clean up aligned control file, if it exists
rm -f $WORK_DIR/temp_aligned.*.${FMTD_REGION}.bam
rm -rf "$ISEC_OUT_DIR"