# This script removes inherited variants called by rufus which lie on the same contig as
# a somatic variant. It accomplishes this task by performing a pileup and variant call
# in the control bam for each of the rufus-identified variants, then taking the complement
# of the control set in an intersection.
set -euo pipefail

: "${WORK_DIR:?WORK_DIR must be set}"

# parse command line arguments
REFERENCE_FILE=""  # Reference file (.fa) - must be the same as RUFUS run that generated RUFUS_VCF
RUFUS_VCF=""       # The 'FINAL' vcf generated by rufus, to be isec'd
OUT_VCF=""
SRC_DIR=""
WINDOW_SIZE="1000"
FMTD_REGION=""
CONTROL_BAM_LIST=() # Remaining args, all control bams
THREADS=10

cleanup() {
    rm -rf "$WORK_DIR"/*_temp_pileups
    rm -f "$WORK_DIR"/temp_aligned.*."$FMTD_REGION".bam
}
trap cleanup EXIT

while getopts "h:f:i:o:w:r:c:t:" option; do 
	case $option in 
		h) usage;;
		f) REFERENCE_FILE=$OPTARG;;
		i) RUFUS_VCF=$OPTARG;;
		o) OUT_VCF=$OPTARG;;
		w) WINDOW_SIZE=$OPTARG;;
		r) FMTD_REGION=$OPTARG;;
		t) THREADS=$OPTARG;;
		c) IFS=',' read -r -a CONTROL_BAM_LIST <<< "$OPTARG";;
		\?) echo "Invalid option: -$OPTARG" >&2
		    usage;;	
		*) echo "Option -$OPTARG requires an argument" >&2
		   usage;;
	esac
done
shift $((OPTIND-1))

if [[ -z "$RUFUS_VCF" ]]; then
	echo "ERROR: Missing required option -i (rufus input vcf)" >&2
	exit 1
fi
if [[ -z "$OUT_VCF" ]]; then
	echo "ERROR: Missing required option -o (output vcf name)" >&2
	exit 1
fi
if [[ -z "$REFERENCE_FILE" ]]; then
	echo "ERROR: Missing required option -f (reference fasta)" >&2
	exit 1
fi
if [[ -z "$FMTD_REGION" ]]; then
	echo "ERROR: Missing required option -r (region)" >&2
	exit 1
fi

# ENV file override
: "${RUFUS_ROOT:=/opt/RUFUS}"

# static vars
CONTROL_VCF="$WORK_DIR/isec_control.$FMTD_REGION.vcf.gz"
NORMED_VCF="$WORK_DIR/normed.$(basename "$RUFUS_VCF")"
BWA="$RUFUS_ROOT/bin/externals/bwa/src/bwa_project/bwa"
PILEUP_SCRIPT="$RUFUS_ROOT/post_process/single_pileup.sh"

# make intersection directory
ISEC_OUT_DIR="$WORK_DIR/temp_${FMTD_REGION}_isecs"
mkdir -p $ISEC_OUT_DIR

#format final rufus vcf for intersections
vt normalize -n "$RUFUS_VCF" -r "$REFERENCE_FILE" | vt decompose_blocksub - | bgzip > "$NORMED_VCF"
bcftools index -t "$NORMED_VCF"

#for loop for each control file provided by user
MERGED_PILEUP="$WORK_DIR/merged_pileup.${FMTD_REGION}.vcf.gz"
SORTED_MERGED_PILEUP="$WORK_DIR/sorted.merged_pileup.${FMTD_REGION}.vcf.gz"

pileups=()
for CONTROL in "${CONTROL_BAM_LIST[@]}"; do
	echo "Piling up $CONTROL" >&2

    MADE_ALIGN_CONTROL=false
	CONTROL_BAM=""

	# Make temp dir for individual pileups
	CONTROL_TAG=$(basename "$CONTROL")
	CONTROL_TAG="${CONTROL_TAG%.bam}"
	CONTROL_TAG=${CONTROL_TAG}.${FMTD_REGION}
	CURR_MERGED_PILEUP="$WORK_DIR/${CONTROL_TAG}.ctrl.merged_pileup.vcf.gz"
	CURR_PILEUP_DIR="$WORK_DIR/${CONTROL_TAG}_temp_pileups"
	CONTROL_ALIGNED="$WORK_DIR/temp_aligned.${CONTROL_TAG}.bam"
 
    #check to see if the provided bam file is aligned
    if [ "$(samtools view -H "$CONTROL" | grep -c '^@SQ')" -gt 0 ]; then
        CONTROL_BAM=$CONTROL
    else
		# TODO: this really needs to be aligned, otherwise we'd be doing this 3000+ times
        "$BWA" mem -t 10 "$REFERENCE_FILE" "$CONTROL" | samtools view -S -@ 12 -b - > "$CONTROL_ALIGNED"
        CONTROL_BAM="$CONTROL_ALIGNED"
	    MADE_ALIGN_CONTROL=true
    fi
    
    # Run pileup and call variants
	echo "Starting parallel mpileup..."
	export PILEUP_SCRIPT CURR_PILEUP_DIR
	
	# Running in WG mode, split pileup by chr
	if [ "$WINDOW_SIZE" -ne 0 ]; then
		# Likely dealing with a small number of variants, send in a single list of sites
		regions=$(bcftools view -H "$NORMED_VCF" | awk '!/^#/ {printf "%s%s:%d-%d", sep, $1, $2, $2; sep="|"} END{print ""}')
		bash $PILEUP_SCRIPT "$regions" "${CONTROL_BAM}" "${REFERENCE_FILE}" > "$CURR_MERGED_PILEUP"
	else
		# Better to do chromosome by chromosome for speed for entire genome
		TEMP_ARGS_FILE="$WORK_DIR/$FMTD_REGION.arguments.txt"
		mkdir -p "$CURR_PILEUP_DIR"
		bcftools query -f '%CHROM\n' "$NORMED_VCF" | sort | uniq | \
		awk -v bam="$CONTROL_BAM" -v ref="$REFERENCE_FILE" '{print $1 "\t" bam "\t" ref}' > "$TEMP_ARGS_FILE"
		cat "$TEMP_ARGS_FILE" | parallel -j +0 --colsep '\t' "bash \"$PILEUP_SCRIPT\" {1} {2} {3} > $CURR_PILEUP_DIR/{1}.vcf.gz"
		for vcf in "$CURR_PILEUP_DIR"/*vcf.gz; do
			bcftools index "$vcf"
		done
		# TODO: this needs to be tested - whole genome 
		bcftools concat -Oz -o "$CURR_MERGED_PILEUP" "$CURR_PILEUP_DIR"/*.vcf.gz
		rm "$TEMP_ARGS_FILE"
		rm -r "$CURR_PILEUP_DIR"
	fi

	bcftools index "$CURR_MERGED_PILEUP"
	pileups+=("$CURR_MERGED_PILEUP")
done

# Combine control specific pileups if there are mutliple
if [ "${#pileups[@]}" -gt 1 ]; then
	echo "about to merge"
	bcftools merge -Oz -o "$MERGED_PILEUP" "${pileups[@]}"
else
	# TODO: this needs to be tested - single control in both modes
	cp "${pileups[0]}" "$MERGED_PILEUP"
fi
rm -f $WORK_DIR/*."$FMTD_REGION".ctrl.merged_pileup.vcf.gz*

# sort combined pileups
bcftools sort -Oz -o "$SORTED_MERGED_PILEUP" "$MERGED_PILEUP"
bcftools index "$SORTED_MERGED_PILEUP"
rm -f $MERGED_PILEUP

# call variants from merged pileup vcf
echo "Starting pileup call..."
bcftools call -cv -Oz -o "$CONTROL_VCF" "$SORTED_MERGED_PILEUP"
bcftools index "$CONTROL_VCF"
rm "$SORTED_MERGED_PILEUP"*

#intersect the control vcf with formatted rufus vcf
CONTROL_RECORD_COUNT=$(bcftools view -H "$CONTROL_VCF" | head -1 | wc -l)
if [ "$CONTROL_RECORD_COUNT" -eq 0 ]; then
	echo "Control VCF has zero variant records — skipping intersection, copying subject VCF directly."
	cp "$NORMED_VCF" "${OUT_VCF}"
	bcftools index -t "$OUT_VCF"
else
	echo "Starting intersection..."
	bcftools isec -Oz -w1 -n=1 -p "$ISEC_OUT_DIR" "$NORMED_VCF" "$CONTROL_VCF"

	# save the new vcf as rufus final vcf
	OUTFILE="$ISEC_OUT_DIR/0000.vcf.gz"
	OUT_INDEX="$ISEC_OUT_DIR/0000.vcf.gz.tbi"

	cp "$OUTFILE" "${OUT_VCF}"
	cp "$OUT_INDEX" "${OUT_VCF}.tbi"
fi
rm "$CONTROL_VCF"*

# clean up aligned control file, if it exists
rm -f $WORK_DIR/temp_aligned.*.${FMTD_REGION}.bam
rm -rf "$ISEC_OUT_DIR"